refactor(lexer.l): replace strdup with malloc and strcpy to avoid memory leaks refactor(main.c): add include statements and main function to run the parser The changes in lexer.l replace the strdup function with malloc and strcpy to avoid memory leaks. The changes in main.c add the necessary include statements and a main function to run the parser.
feat(picolang): add label and temporary register generation functions, add string creation function, add function to trim newline characters from strings
This commit adds functions to generate labels and temporary registers, which are used in the parser to generate code. A function to create strings is also added to simplify string allocation. Lastly, a function to trim newline characters from strings is added to ensure consistency in the generated code.

refactor(xmake.lua): remove commented out code and unused variables, set default build mode to releasedbg
The commented out code and unused variables have been removed to improve code readability. The default build mode has been set to releasedbg to ensure that the build is optimized for performance.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,3 +1,20 @@
-#!/usr/bin/bash
+#!/bin/bash
 
-./app/app_test
+usage() {
+    echo -e "Usage: $0" 1>&2
+    exit 1
+}
+
+command_exists() {
+    if ! command -v """$1" >/dev/null 2>&1; then
+        echo "I require the command ""$1 but it's not installed. Abort."
+        exit 1
+    fi
+}
+
+command_exists "flex"
+command_exists "bison"
+command_exists "gcc"
+command_exists "make"
+
+# Make
